// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmfEhhzdPOTqN784AGyOfzq9ibUdqivZo',
    appId: '1:356218597939:web:af7d894c558a317f1aa946',
    messagingSenderId: '356218597939',
    projectId: 'profanity-checker-app',
    authDomain: 'profanity-checker-app.firebaseapp.com',
    storageBucket: 'profanity-checker-app.appspot.com',
    measurementId: 'G-V4FDG97HM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4Yy_sUg1DP1zJ2rWKXmtRVBar-FdTCjk',
    appId: '1:356218597939:android:ece52e5b6b5d3b891aa946',
    messagingSenderId: '356218597939',
    projectId: 'profanity-checker-app',
    storageBucket: 'profanity-checker-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChgKmrk_O8f2U7ExA0A52j0XcmC1daiQ4',
    appId: '1:356218597939:ios:8f1a2c10697ed7da1aa946',
    messagingSenderId: '356218597939',
    projectId: 'profanity-checker-app',
    storageBucket: 'profanity-checker-app.appspot.com',
    iosClientId: '356218597939-2msq6is7mh3k1ifq3tkflrcce9ehlgi4.apps.googleusercontent.com',
    iosBundleId: 'com.example.profanityDetectorDemoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChgKmrk_O8f2U7ExA0A52j0XcmC1daiQ4',
    appId: '1:356218597939:ios:8f1a2c10697ed7da1aa946',
    messagingSenderId: '356218597939',
    projectId: 'profanity-checker-app',
    storageBucket: 'profanity-checker-app.appspot.com',
    iosClientId: '356218597939-2msq6is7mh3k1ifq3tkflrcce9ehlgi4.apps.googleusercontent.com',
    iosBundleId: 'com.example.profanityDetectorDemoApp',
  );
}
